//! The offline license gate.
//!
//! WARDEN is bought once and verified locally, forever. Nothing in this module
//! opens a socket, and nothing in it ever will: an activation server would
//! contradict the app's whole claim (`CLAUDE.md`: "No network until you ask for
//! one") and would turn a one-time purchase into a thing that stops working when
//! a domain lapses. The full contract is `docs/LAUNCH-SPEC.md` section 2.
//!
//! Four pieces, deliberately separated so the risky one is pure:
//!
//! * [`verify`] is the whole of the cryptography: parse `WRDN-<payload>.<sig>`,
//!   check Ed25519 against the compiled-in public key, check `v == 1`. No IO, no
//!   clock, no state. Tested against `docs/license-vectors.json`, the same file
//!   the Node signer is tested against, read at test time so producer/consumer
//!   drift fails a test rather than a customer.
//! * [`store`] is `~/.warden/license`: read on launch, written atomically on a
//!   successful activation. Absent or corrupt means the activation screen.
//! * [`gate`] is the decision, and the canary that proves the decision has no
//!   input but the stored key and the compile-time profile.
//! * [`commands`] is the two-command IPC surface the activation screen uses.
//!
//! [`pubkey`] is GENERATED by `scripts/gen-license-keypair.mjs`. Never edit it by
//! hand: it and `docs/license-vectors.json` are written in the same run and a
//! test asserts they still agree.
//!
//! What this gate is NOT: it is not DRM. An offline check is bypassable by
//! anyone willing to patch the binary, and that is a deliberate, accepted trade.
//! It exists so an honest buyer's key works on a plane, not so a determined one
//! is stopped.

pub mod commands;
pub mod gate;
pub mod pubkey;
pub mod store;
pub mod verify;

// The two `#[tauri::command]` functions are deliberately NOT re-exported here:
// the macro emits companion items beside each function, and `generate_handler!`
// needs the defining path (`license::commands::license_status`), so a shortcut
// re-export would only look like it worked.
pub use commands::LicenseStatus;
pub use gate::{allows, command_is_allowed, status, GateStatus, GATE_ENABLED};
pub use verify::{verify_key, LicenseClaims, LicenseError};
